# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  ci: true

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'
    workingDirectory: my-app

  - script: |
      npm test
    displayName: 'npm test'
    workingDirectory: my-app

  - script: |
      npm run build
    displayName: 'build'
    workingDirectory: my-app

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/my-app/build'
      ArtifactName: 'drop'
